### ISSUE TITLE
Running as Service on Windows

### ISSUE THREAD

**Issue by peeyush-es** [exact-space/opc-agent-installer#1]
https://dzone.com/articles/installing-a-java-application-as-a-windows-service

**Comment by Sudharshan-ES** [comment]
No project and/or card associated with this ticket. Please take necessary action.

**Comment by Sudharshan-ES** [comment]
No developer assigned to this ticket. Please take necessary action.

**Comment by Sudharshan-ES** [comment]
No project and/or card associated with this ticket. Please take necessary action.

**Comment by Sudharshan-ES** [comment]
No developer assigned to this ticket. Please take necessary action.

**Comment by Sudharshan-ES** [comment]
@arun-es No project and/or card associated with this ticket.

**Comment by Sudharshan-ES** [comment]
@arun-es No project and/or card associated with this ticket.
